version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: accounting-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: accounting
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build:
      context: .
    container_name: java-app
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
